version: "3.8"

services:
  client:
    build: ./client
    container_name: profile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - app-network
    working_dir: /app

  server:
    build: ./server
    container_name: pback
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - app-network
    working_dir: /app

networks:
  app-network:
    driver: bridge
