version: "3.8"

services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
   
    depends_on:
      - server

  server:
    build: 
      context: ./server
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mongodb+srv://souvik3469:souvik3469@cluster0.j6tmyo5.mongodb.net/test1
      - USER_ACCESS_SECRET=duocortex
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: ankushDb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
